<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerVVDCxi8\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerVVDCxi8/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerVVDCxi8.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerVVDCxi8\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerVVDCxi8\App_KernelDevDebugContainer([
    'container.build_hash' => 'VVDCxi8',
    'container.build_id' => 'e5631601',
    'container.build_time' => 1606491762,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerVVDCxi8');
