<?php

// This file has been auto-generated by the Symfony Cache Component.

return [[

'_default' => 0,

], [

0 => [
    'entrypoints' => [
        'basic' => [
            'js' => [
                '/build/runtime.js',
                '/build/basic.js',
            ],
            'css' => [
                '/build/basic.css',
            ],
        ],
        'home' => [
            'js' => [
                '/build/runtime.js',
                '/build/home.js',
            ],
            'css' => [
                '/build/home.css',
            ],
        ],
    ],
],

]];
